## gastrointestinal_hdn.R     6/12/16
## load in files for Gastrointestinal disease (hdn=human disease network) and gene lists
##    source("http://bioconductor.org/biocLite.R")
##    biocLite("whatever")
## NOTE: tree structure is generated from meshtree.R file.
## NCBI2R must be downloaded from CRAN archive https://cran.r-project.org/src/contrib/Archive/NCBI2R/

library(igraph)
library(linkcomm)
library(dplyr)
library(tidyr)
library(xtable)
library(ggplot2)
library(rentrez)
library(org.Hs.eg.db)
library(clusterProfiler)
library(ReactomePA)
library(NCBI2R)

# Saved data generated by meshtree.R workspace at this point in R-files/disease/ and its called....
# GI-disease-Oct21st2017.RData
# load it in using below line of code.
load("C:/R-files/disease/GI-disease-Oct21st2017.RData")


#----------------- use OMIM database (via rentrez) to generate list of implicated disease genes for each disease -----------
entrez_db_searchable("omim")
Dproteins <- c("TNF","HRH2","APC","MLN","CDKN2A")   # crud<-c("7124","3274","324","1029","9318","79026","1654","65003","6240","3476","6238","3836")

#x <- entrez_search(db="omim", term="126850[GENE]",retmax=2000)

# Obtain ReactomePA pathways
genelist <- bitr(Dproteins,fromType = "SYMBOL",toType="ENTREZID",OrgDb="org.Hs.eg.db")
genelist <- genelist[2]
genelist <- sapply(genelist, as.character)
genelist <- as.character(unname(genelist, force = TRUE))
genelist<- as.character(genelist)
pathways <- enrichPathway(genelist, pvalueCutoff=0.1,organism="human",readable=TRUE)
head(yy)

temparticlecount <- count_articles(Dproteins) # how many articles written about these proteins?
tempinteractions <- get_interactions(Dproteins)
tempintcount <- count_interactions(Dproteins)

# ============= FUNCTIONS HERE ==================================

# Calculate some statistics about the disease gene network
get_gstatistics <- function(gt) {
  gstats <- data.frame(
    modularity=modularity(gt, membership(cluster_walktrap(gt))),
    avepath=average.path.length(gt),
    nedges=ecount(gt),
    nverts=vcount(gt),
    transit=transitivity(gt),
    avedegree=mean(degree(gt)),
    diameter=diameter(gt,weights=NA),
    connect=is.connected(gt),
    closeness=closeness(gt),
    betweenness=betweenness(gt,directed=FALSE),
    density=graph.density(gt),
    hubness=hub_score(gt)$vector,
    authority=authority.score(gt)$vector)
  #power=bonpow(gt))
  return(gstats)
}

# Count how many interactions each protein has. Uses NCBI2R package..
count_interactions <- function(CVDP) {
  for (i in 1:length(CVDP)){
    print(CVDP[i])
    pname <- paste(CVDP[i],'[sym]',sep="")
    ids<-GetIDs(pname)
    plist<-GetInteractions(ids[1])
    plist<-unique(plist[13])
    ptemp <- cbind(CVDP[i],nrow(plist))
    
    if(i!=1){
      ppi <- rbind(ppi,ptemp)} 
    else{
      ppi <- ptemp}
  }
  
  return(ppi)
}

# For each disease protein get the proteins they interact with. Uses NCBI2R package.
get_interactions <- function(CVDP){
  
  for (i in 1:length(CVDP)){
    print(CVDP[i])
    pname <- paste(CVDP[i],'[sym]',sep="")
    ids<-GetIDs(pname)
    plist<-GetInteractions(ids)
    
    plist<-unique(plist[13])
    #print(plist)
    cvd<-rep(CVDP[i],nrow(plist))
    ptemp <- cbind(cvd,plist)
    
    if(i!=1){
      ppi <- rbind(ppi,ptemp)} 
    else{
      ppi <- ptemp}
  }
  
  return(ppi)
}



# See how many research articles are written about our proteins. Uses rentrez package.
count_articles <- function (CVDP){
  for (i in 1:length(CVDP)){
    
    print(CVDP[i])
    pname <- paste(CVDP[i],'[GENE]) AND (Homo sapiens[ORGN])',sep="")
    ids<-entrez_search(db="pubmed", term=pname,retmax=90000)
    atemp <- cbind(CVDP[i],length(ids$ids))
    
    if(i!=1){
      articles <- rbind(articles,atemp)} 
    else{
      articles <- atemp}
  }
  return(articles)
}



# R provides a tail and head command to view last six and first six elements, so why not a middle?
middle <- function(mydata) {
  len <- nrow(mydata)
  startpoint <- round(len/2)
  endpoint <- startpoint+5
  mydata[startpoint:endpoint,]
  
}



